### ISSUE TITLE
Add documentation for "Configure Contracts" page

### ISSUE THREAD

**Issue by metalboyrick** [Scaffold-Stark/ss2-docs#21]
## Issue Overview

We have a new page called Configure Contracts which you can click on the bottom of the screen. This page allows people to pull existing contract from the network and incorporate it into their Scaffold-Stark project. We are missing documentation here.

## Proposed Solutions or Ideas

- Your documentation should be clear and concise.
- Use images where appropriate
- Use proper styling and hierarchy for text
- Use proper styling for code and variable names.
- Use proper callouts when required

Refer to docusaurus for more info: https://docusaurus.io/

**Comment by Benjtalkshow** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/speedrun-scaffold-stark).

### My background and how it can be leveraged
I’m Benjamin, and I’m ready to work on creating documentation for the new Configure Contracts page in our project. Since joining OnlyDust, I’ve made 20 contributions, and I trust in my ability to create clear and concise documentation that enhances the user experience.

### How I plan on tackling this issue
What will plan to achieve is to  write documentation for the Configure Contracts page, which allows users to pull existing contracts from the network and integrate them into their Scaffold-Stark project right?

Here’s how i plan to tackle this issue:
1. I will write clear, step-by-step instructions on how users can access the page, pull contracts, and incorporate them into their project.
2. I will add images or GIFs where appropriate to visually guide users through the process.
3. I will ensure proper styling of the text, with appropriate hierarchy, code, and variable names to make the content clean and professional.
4. I will also include callouts for important tips, notes, or warnings to help users avoid common pitfalls.

5. I will alos  follow best practices for documentation from Docusaurus to ensure the layout is user-friendly and well-structured.
Once I’ve completed the documentation, I’ll review it thoroughly to ensure it’s easy to understand and aligned with the project’s guidelines. Then, I’ll make a PR for feedback and approval. Thanks.

**Comment by Nadai2010** [comment]
All your @mexes20

**Comment by metalboyrick** [comment]
Hi @mexes20  , sorry for rushing in but we would like to remind you that ODHack8 is almost finished :( would encourage to start working on this issue and put out a PR ASAP, thanks in advance!
