### ISSUE TITLE
Add documentation on Block Explorers

### ISSUE THREAD

**Issue by metalboyrick** [Scaffold-Stark/ss2-docs#25]
## Issue Overview

Users can now access block explorers from our framework, kindly write a small note about this.

## Proposed Solutions or Ideas

- Your documentation should be clear and concise.
- Use images where appropriate
- Use proper styling and hierarchy for text
- Use proper styling for code and variable names.
- Use proper callouts when required

Refer to docusaurus for more info: https://docusaurus.io/

**Comment by raizo07** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/speedrun-scaffold-stark).

### My background and how it can be leveraged
Hello, I'll like to be assigned to work on this

**Comment by devcollinss** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/speedrun-scaffold-stark).

### My background and how it can be leveraged
My name is Collins Ikechukwu. I'm a full stack blockchain developer developer and a technical writer

### How I plan on tackling this issue
I will write a clear and concise note about the new feature that allows users to access block explorers from our framework. I will structure the note to highlight the key functionalities and benefits of this feature, using proper styling and hierarchy for text to enhance readability.

Where appropriate, I will include images to provide visual examples of the block explorer integration, ensuring users can easily understand how to utilize this feature. I will also use appropriate styling for any code snippets or variable names to differentiate them from regular text.

Additionally, I will incorporate callouts to emphasize important points or tips related to using the block explorers. To ensure a polished presentation, I will refer to Docusaurus for best practices in documentation structure and styling. After drafting the note, I will review it for clarity and completeness before finalizing it.

**Comment by Benjtalkshow** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/speedrun-scaffold-stark).

### My background and how it can be leveraged
I’m Benjamin, and I’m ready to work on adding documentation about the new block explorer feature in our framework. Since joining OnlyDust, I’ve contributed significantly to improving our documentation, and I’m confident this addition will help users better navigate the new functionality.

### How I plan on tackling this issue
The goal is to write a concise and clear explanation of how users can access and use block explorers directly from our framework. I’ll provide a brief overview of what block explorers are, how they work, and why they’re useful for viewing blockchain data. This will help users understand the context and importance of the feature.

To make the documentation more user-friendly, I will incorporate images that demonstrate how to access the block explorer from the interface. I’ll ensure the document uses proper styling, with well-structured text, code snippets, and variable names clearly formatted for easy readability. Additionally, I’ll include callouts for any important tips or warnings, so users can easily follow the instructions without missing key details.

I’ll refer to `Docusaurus` to maintain best practices for organizing and styling the documentation. Once I finish, I’ll review the content to ensure it’s accurate, easy to understand, and aligned with our standards. Afterward, I’ll submit a PR for feedback and refinement.

**Comment by Nadai2010** [comment]
Hi since @Benjtalkshow has applied in several previous issues in order, this time we will assign it to him

**Comment by Benjtalkshow** [comment]
> Hi since @Benjtalkshow has applied in several previous issues in order, this time we will assign it to him

Thanks a lot. we work on it asap

**Comment by metalboyrick** [comment]
Hi @Benjtalkshow  , sorry for rushing in but we would like to remind you that ODHack8 is almost finished :( would encourage to start working on this issue and put out a PR ASAP, thanks in advance!

**Comment by Benjtalkshow** [comment]
> Hi @Benjtalkshow , sorry for rushing in but we would like to remind you that ODHack8 is almost finished :( would encourage to start working on this issue and put out a PR ASAP, thanks in advance!

Alright thanks

**Comment by Benjtalkshow** [comment]
Hello @metalboyrick 
Can you provide more details about the  `block explorers` you mentioned in this task.
