### ISSUE TITLE
Document `useScaffoldEthBalance` and `useScaffoldStrkBalance`

### ISSUE THREAD

**Issue by metalboyrick** [Scaffold-Stark/ss2-docs#26]
## Issue Overview

Update documentations for the two hooks above.

## Proposed Solutions or Ideas

- Your documentation should be clear and concise.
- Use images where appropriate
- Use proper styling and hierarchy for text
- Use proper styling for code and variable names.
- Use proper callouts when required

Refer to docusaurus for more info: https://docusaurus.io/

**Comment by Calebux** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/speedrun-scaffold-stark).

### My background and how it can be leveraged
I wrote joyboy's documentation using Docusaurus and can take this head on

### How I plan on tackling this issue
Write the documentation following the prescribed guide

**Comment by ShantelPeters** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/speedrun-scaffold-stark).

### My background and how it can be leveraged
I am frontend developer and also skilled in technical documetation.i have a good understanding with technologies like Html, css, javascript, typescript , cario  . i have also successfully contributed to open source projects like arkproject, stark Quest, shinigami.

### How I plan on tackling this issue
To update the documentation i will carry out the following : 
1. Write clearly,and include simple examples.
2. Use images (diagrams/screenshots) where needed.
3.Structure with headings and styled text for emphasis.
4. Format code properly using code blocks and clear variable names.
5. Add callouts for important notes or warning.
Then create a pull request and request for a review .

**Comment by estherbreath** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/speedrun-scaffold-stark).

### My background and how it can be leveraged
I am a smart contract developer and a technical writer.
I attended and came out with a gold medal from the prestigious Ethereum Writers Cohort 2023.
Leveraging on my knowledge, I have published articles and participated in hackathons as a developer and a technical writer.
I will leverage on my experiences to get this issue done well, and in a good time.

### How I plan on tackling this issue
I will take the steps below to get the documentation done.
    1. Create Markdown files in the directory for the documentation pages. 
    2. Use front matter to provide metadata for each doc page, including title, description, and slug
    3. Use proper heading hierarchy (H1, H2, etc.) for clear document structure. 
    4. Include code blocks and images where necessary. 
    5. Style the documentation appropriately.
    6. Write clearly and concisely, avoiding unnecessary details.

**Comment by Benjtalkshow** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/speedrun-scaffold-stark).

### My background and how it can be leveraged
I’m Benjamin, and I’m ready to update the documentation for the two hooks mentioned in this issue. With 20 contributions to OnlyDust, I’m confident that I can enhance the clarity and usability of these hooks’ documentation.

### How I plan on tackling this issue
The goal of this task is to revise the documentation for the two hooks, making it clear, concise, and easy for users to understand and implement. I will start by providing detailed explanations of each hook, covering what they do, how they work, and what parameters and return values are involved. By focusing on simplicity and clarity, I aim to ensure that users can easily grasp the purpose and functionality of the hooks.

In addition to the written descriptions, I will include images or diagrams where necessary to visually demonstrate how to use the hooks. This will help users better understand the process and enhance their overall experience. I’ll also ensure the documentation uses proper styling, with attention to text hierarchy, code formatting, and variable names, so that it remains clean and professional throughout.

Furthermore, I will include callouts to highlight important tips, best practices, and potential pitfalls. These will serve as useful guides for users, helping them avoid common mistakes and improving their workflow. To ensure consistency, I’ll adhere to the best practices from Docusaurus, which provides helpful guidelines on documentation structure and formatting.

Once the updates are complete, I will review the entire documentation thoroughly to make sure everything is clear, accurate, and aligned with the project’s standards. After that, I will submit a PR for feedback and review, ensuring that the new documentation meets the needs of our users and improves the overall experience with the hooks.

**Comment by Nadai2010** [comment]
Hi, all your @estherbreath
